# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#a6d189)\
$directory\
[](fg:#a6d189 bg:#81c8be)\
$git_branch\
$git_status\
[](fg:#81c8be bg:#babbf1)\
$time\
[ ](fg:#babbf1)\
$fill\
$lua\
$golang\
$nodejs\
$jobs\
$cmd_duration\
$line_break\
$character"""

# Inserts a blank line between shell prompts
add_newline = false 

[directory]
style = 'bg:#a6d189 fg:#303446'
format = '[$path ]($style)'
truncate_to_repo = false

[directory.substitutions]
"Projects" = ''
"~" = "󱐋"

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[➜](bold red) "
vicmd_symbol = "[V](bold yellow) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[golang]
format = "[$symbol$version](bold cyan) "
symbol = " "

[dotnet]
disabled = true

[nodejs]
symbol = " "
format = "[$symbol$version](bold green) "

[lua]
symbol = ' '

[fill]
symbol = " "

[git_branch]
style = 'bg:#81c8be fg:#303446'
symbol = ' '
format = '[ $symbol$branch]($style)'

[git_status]
style = 'bg:#81c8be fg:#303446'
format = "[ $all_status$ahead_behind ]($style)"

[time]
disabled = false
style = "bg:#babbf1 fg:#303446"
format = '[  $time ]($style)'
use_12hr = false
time_format = '%d/%m %I:%M'
