# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_frappe"

format = """
[](green)\
$directory\
[](fg:green bg:teal)\
$git_branch\
$git_status\
$git_metrics\
[](fg:teal bg:sapphire)\
$time\
[ ](fg:sapphire)\
$fill\
$lua\
$golang\
$nodejs\
$jobs\
$cmd_duration\
$line_break\
$character"""

# Inserts a blank line between shell prompts
add_newline = false 

[directory]
style = 'bg:green fg:crust'
format = '[$path ]($style)'
truncate_to_repo = false

[directory.substitutions]
"Projects" = ''
"~" = "󱐋"

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[➜](bold red) "
vicmd_symbol = "[V](bold yellow) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[golang]
format = "[$symbol$version](bold cyan) "
symbol = " "

[dotnet]
disabled = true

[nodejs]
symbol = " "
format = "[$symbol$version](bold green) "

[lua]
symbol = ' '

[fill]
symbol = " "

[git_branch]
style = 'bg:teal fg:crust'
symbol = ' '
format = '[ $symbol$branch]($style)'

[git_status]
style = 'bg:teal fg:crust'
format = "[ $all_status$ahead_behind ]($style)"

[git_metrics]
added_style = 'bg:teal fg:crust'
deleted_style = 'bg:teal fg:crust'
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))' 
disabled = false

[time]
disabled = false
style = "bg:sapphire fg:crust"
format = '[  $time ]($style)'
use_12hr = false
time_format = '%d/%m %I:%M'


[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
